#!/usr/bin/env python3
import time
from datetime import datetime
import sqlite3
from easysnmp import Session



def main():
    while True:
        try:
            connect_to_database = sqlite3.connect('track-a-mac.db') # create or open track-a-mac database
            print("connected to database!")
        except sqlite3.Error as error:
            print(error)
        
            
            

if __name__ == '__main__':
    main()